import { Colors } from "@/src/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  scroll: { flexGrow: 1, paddingBottom: 40 },

  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4 },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.shadow,
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  backArrow: { fontSize: 20, color: Colors.primary },

  iconArea: {
    alignItems: "center",
    justifyContent: "center",
    height: 136,
    marginTop: 20,
    position: "relative",
  },
  iconCircle: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: Colors.primarySurface,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.primary,
    shadowOpacity: 0.15,
    shadowRadius: 14,
    elevation: 4,
  },
  iconEmoji: { fontSize: 50 },
  badge: {
    position: "absolute",
    top: 10,
    right: "26%",
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: Colors.success,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2.5,
    borderColor: Colors.background,
  },
  badgeText: { fontSize: 14, color: Colors.textOnPrimary, fontWeight: "700" },
  sparkle: { position: "absolute", fontSize: 16, color: Colors.primary, opacity: 0.55 },

  card: {
    marginHorizontal: 20,
    backgroundColor: Colors.surface,
    borderRadius: 24,
    padding: 24,
    shadowColor: Colors.shadow,
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 4,
    marginTop: 8,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.textPrimary,
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: "center",
    marginBottom: 12,
  },
  emailPill: {
    alignSelf: "center",
    backgroundColor: Colors.primarySurface,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 9,
    marginBottom: 16,
    maxWidth: "90%",
  },
  emailText: { fontSize: 14, fontWeight: "700", color: Colors.primary },
  instrucao: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  instrucaoBold: { fontWeight: "700", color: Colors.primary },

  divider: { height: 1, backgroundColor: Colors.border, marginVertical: 20 },

  reenviarLabel: {
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: "center",
    marginBottom: 12,
  },
  reenviadoBadge: {
    alignSelf: "center",
    backgroundColor: Colors.successBg,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Colors.success,
  },
  reenviadoText: { fontSize: 12, color: Colors.success, fontWeight: "600" },

  btnReenviar: {
    alignSelf: "center",
    borderWidth: 1.5,
    borderColor: Colors.primary,
    borderRadius: 14,
    paddingHorizontal: 28,
    paddingVertical: 12,
    marginBottom: 16,
  },
  btnReenviarLoading: { borderColor: Colors.textMuted },
  btnReenviarText: { fontSize: 14, fontWeight: "700", color: Colors.primary },

  countdownBox: {
    alignSelf: "center",
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 16,
  },
  countdownText: { fontSize: 13, color: Colors.textSecondary },
  countdownNum: { fontWeight: "700", color: Colors.primary },

  btnLogin: {
    backgroundColor: Colors.primary,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    shadowColor: Colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  btnLoginText: { fontSize: 16, fontWeight: "700", color: Colors.textOnPrimary },

  avisoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: Colors.warningBg,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.warning,
  },
  avisoEmoji: { fontSize: 15, marginRight: 8, marginTop: 1 },
  avisoText: { flex: 1, fontSize: 13, color: Colors.warning, lineHeight: 18 },
  avisoBold: { fontWeight: "700" },

  trocarEmailRow: { alignItems: "center", marginTop: 16 },
  trocarEmailText: { fontSize: 13, color: Colors.primary, textDecorationLine: "underline" },
});
